(()=>{'use strict';const $=x=>document.getElementById(x),K='atlas-gpx-v1',W='atlas-walk-v8',J='atlas-journal-v8';let pts=[],walk=[],map,route,halo,walkLine,returnLine,marker,watch=null,heading=null,compass=false,started=0,timer,dist=[],total=0,progress=0,offCount=0,lastAlert=0,eco=false,layer;const rad=Math.PI/180,fmt=n=>n>=1000?(n/1000).toFixed(2)+' km':Math.round(n)+' m',get=k=>{try{return JSON.parse(localStorage.getItem(k)||'null')}catch{return null}},put=(k,v)=>{try{localStorage.setItem(k,JSON.stringify(v));return true}catch{return false}},msg=s=>$('status').textContent=s;function distance(a,b){let x=(b.lat-a.lat)*rad,y=(b.lon-a.lon)*rad,z=Math.sin(x/2)**2+Math.cos(a.lat*rad)*Math.cos(b.lat*rad)*Math.sin(y/2)**2;return 12742000*Math.atan2(Math.sqrt(z),Math.sqrt(1-z))}function bearing(a,b){return (Math.atan2(Math.sin((b.lon-a.lon)*rad)*Math.cos(b.lat*rad),Math.cos(a.lat*rad)*Math.sin(b.lat*rad)-Math.sin(a.lat*rad)*Math.cos(b.lat*rad)*Math.cos((b.lon-a.lon)*rad))/rad+360)%360}
function parse(s){let d=new DOMParser().parseFromString(s,'application/xml');if(d.querySelector('parsererror'))throw Error('XML invalide');let n=[...d.getElementsByTagName('trkpt')];if(!n.length)n=[...d.getElementsByTagName('rtept')];let p=n.map(e=>{let el=e.getElementsByTagName('ele')[0];return {lat:+e.getAttribute('lat'),lon:+e.getAttribute('lon'),ele:el?+el.textContent:null}}).filter(x=>Number.isFinite(x.lat)&&Number.isFinite(x.lon)&&Math.abs(x.lat)<=90&&Math.abs(x.lon)<=180);if(p.length<2)throw Error('Pas de points GPS');return p}
function prep(){dist=[0];for(let i=1;i<pts.length;i++)dist.push(dist.at(-1)+distance(pts[i-1],pts[i]));total=dist.at(-1);profile();turns()}
function nearest(p){let best={d:Infinity,m:0};for(let i=1;i<pts.length;i++){let a=pts[i-1],b=pts[i],c=Math.cos(p.lat*rad),ax=a.lon*c,ay=a.lat,bx=b.lon*c,by=b.lat,t=Math.max(0,Math.min(1,((p.lon*c-ax)*(bx-ax)+(p.lat-ay)*(by-ay))/((bx-ax)**2+(by-ay)**2||1))),q={lat:a.lat+t*(b.lat-a.lat),lon:a.lon+t*(b.lon-a.lon)},d=distance(p,q);if(d<best.d)best={d,m:dist[i-1]+t*(dist[i]-dist[i-1])}}return best}
function profile(){let svg=$('profile'),els=pts.map(p=>p.ele);if(!pts.length||els.filter(Number.isFinite).length<pts.length*.8){svg.innerHTML='<text x="20" y="80" fill="#81918a">Altitudes absentes du GPX</text>';return}let sm=els.map((v,i)=>{let x=els.slice(Math.max(0,i-3),i+4).filter(Number.isFinite);return x.reduce((a,b)=>a+b,0)/x.length}),lo=Math.min(...sm),hi=Math.max(...sm),rng=Math.max(15,hi-lo),poly=sm.map((v,i)=>`${20+560*dist[i]/total},${150-120*(v-lo)/rng}`).join(' ');svg.innerHTML=`<line x1="20" y1="150" x2="580" y2="150" stroke="#cbd8d0"/><polyline points="${poly}" fill="none" stroke="#d12b67" stroke-width="3"/><text x="20" y="15" fill="#638071">${Math.round(hi)} m</text><text x="20" y="170" fill="#638071">${Math.round(lo)} m</text>`}
function turns(){let el=$('turns');el.replaceChildren();if(!pts.length){el.textContent='Importer GPX';return}let count=0,last=-500;for(let i=7;i<pts.length-7;i+=4){let before=bearing(pts[i-7],pts[i]),after=bearing(pts[i],pts[i+7]),ang=((after-before+540)%360)-180;if(Math.abs(ang)>55&&dist[i]>progress+20&&dist[i]-last>170){let row=document.createElement('div');row.className='turn';row.textContent=(ang>0?'↱ Virage à droite':'↰ Virage à gauche')+' dans '+fmt(dist[i]-progress)+' · indicatif, pas une intersection vérifiée';el.append(row);last=dist[i];if(++count===4)break}}if(!count)el.textContent='Pas de virage marqué détecté (les intersections ne sont pas garanties).'}
function draw(){if(!map||!pts.length)return;[route,halo].forEach(l=>l&&map.removeLayer(l));let coords=pts.map(p=>[p.lat,p.lon]);halo=L.polyline(coords,{color:'#fff',weight:12,interactive:false}).addTo(map);route=L.polyline(coords,{color:'#d12b67',weight:6}).addTo(map);map.fitBounds(route.getBounds(),{padding:[40,40]})}
function drawWalk(){if(!map)return;if(walkLine)map.removeLayer(walkLine);if(walk.length>1)walkLine=L.polyline(walk.map(p=>[p.lat,p.lon]),{color:'#176dd4',weight:3,dashArray:'6 5'}).addTo(map);$('walkInfo').textContent=walk.length+' points enregistrés'}
function initMap(){if(!window.L){$('noMap').textContent='Carte indisponible (connexion nécessaire pour Leaflet)';return}map=L.map('map',{zoomControl:false}).setView([43.335,5.75],11);const layers={voyager:L.tileLayer('https://{s}.basemaps.cartocdn.com/rastertiles/voyager/{z}/{x}/{y}{r}.png',{subdomains:'abcd',maxZoom:19,attribution:'© OpenStreetMap contributors · © CARTO'}),topo:L.tileLayer('https://{s}.tile.opentopomap.org/{z}/{x}/{y}.png',{maxNativeZoom:17,maxZoom:19,attribution:'© OpenStreetMap contributors · OpenTopoMap'}),osm:L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'© OpenStreetMap contributors'})};layer=layers.voyager.addTo(map);$('base').onchange=e=>{map.removeLayer(layer);layer=layers[e.target.value].addTo(map);layer.bringToBack()};$('noMap').remove();draw();drawWalk()}
function updateHeading(){let a=marker?.getElement()?.querySelector('span');if(a){a.style.transform=`rotate(${heading||0}deg)`;a.style.opacity=heading===null?'.25':'1'}$('heading').textContent=heading===null?'—':Math.round(heading)+'°'}
function orientation(e){let n=Number.isFinite(e.webkitCompassHeading)?e.webkitCompassHeading:e.absolute===true&&Number.isFinite(e.alpha)?(360-e.alpha)%360:null;if(n!==null){heading=n;updateHeading()}}
function gpsUpdate(g){let c=g.coords,p={lat:c.latitude,lon:c.longitude,ele:c.altitude,acc:c.accuracy,t:Date.now()};$('accuracy').textContent='±'+Math.round(p.acc)+' m';$('speed').textContent=Number.isFinite(c.speed)?(c.speed*3.6).toFixed(1)+' km/h':'—';$('altitude').textContent=Number.isFinite(c.altitude)?Math.round(c.altitude)+' m':'—';if(!compass&&Number.isFinite(c.heading)&&c.speed>1.2)heading=c.heading;if(map){if(marker)map.removeLayer(marker);marker=L.marker([p.lat,p.lon],{zIndexOffset:1000,icon:L.divIcon({className:'',html:'<div class="gpsArrow"><span style="display:block">▲</span></div>',iconSize:[40,40],iconAnchor:[20,20]})}).addTo(map)}updateHeading();window._atlasLast=p;
if(!walk.length||distance(walk.at(-1),p)>(eco?15:5)){walk.push(p);if(walk.length>12000)walk=walk.slice(-12000);put(W,walk);drawWalk()}
if(!pts.length){msg('GPS actif · importer le GPX');return}let n=nearest(p);progress=n.m;$('progress').textContent=fmt(progress);$('remaining').textContent=fmt(Math.max(0,total-progress));$('offset').textContent=fmt(n.d);let secs=Math.max(1,(Date.now()-started)/1000),v=progress/secs;$('eta').textContent=v>.3&&n.d<1000?new Date(Date.now()+(total-progress)/v*1000).toLocaleTimeString('fr-FR',{hour:'2-digit',minute:'2-digit'}):'—';turns();if(n.d>2000){offCount=0;msg('GPS actif · loin du parcours, alerte désactivée')}else if(n.d>Math.max(65,3*p.acc)&&p.acc<45){if(++offCount>=3){msg('⚠ Écart '+fmt(n.d)+' : vérifiez le terrain et le balisage');if($('alert').checked&&Date.now()-lastAlert>60000){navigator.vibrate?.([250,100,250]);lastAlert=Date.now()}}}else{offCount=0;msg('GPS actif · écart '+fmt(n.d)+' · précision ±'+Math.round(p.acc)+' m')}}
function stop(){if(watch!==null)navigator.geolocation.clearWatch(watch);watch=null;clearInterval(timer);$('gpsBtn').textContent='⌖ Démarrer GPS';msg('GPS arrêté · positions sauvegardées')}
function start(){if(!navigator.geolocation){msg('GPS non disponible');return}started=Date.now();watch=navigator.geolocation.watchPosition(gpsUpdate,e=>msg('Erreur GPS : '+e.message),{enableHighAccuracy:!eco,maximumAge:eco?15000:3000,timeout:25000});$('gpsBtn').textContent='■ Arrêter GPS';timer=setInterval(()=>{let m=Math.floor((Date.now()-started)/60000);$('elapsed').textContent=String(Math.floor(m/60)).padStart(2,'0')+':'+String(m%60).padStart(2,'0')},15000)}
function download(name,content,type){let url=URL.createObjectURL(new Blob([content],{type})),a=document.createElement('a');a.href=url;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),4000)}
function entries(){let el=$('entries');el.replaceChildren();(get(J)||[]).slice().reverse().forEach(x=>{let d=document.createElement('div');d.className='journalEntry';let b=document.createElement('b'),p=document.createElement('p');b.textContent=x.name+' · '+x.rating+'/5';p.textContent=x.date+' — '+x.notes;d.append(b,p);el.append(d)})}
function init(){pts=get(K)||[];if(!Array.isArray(pts))pts=[];pts=pts.filter(p=>Number.isFinite(p.lat)&&Number.isFinite(p.lon));walk=get(W)||[];if(!Array.isArray(walk))walk=[];if(pts.length>1)prep();initMap();entries();$('date').value=new Date().toISOString().slice(0,10);if(pts.length)msg('GPX restauré · '+pts.length+' points · '+fmt(total));$('walkInfo').textContent=walk.length+' points enregistrés';
$('import').onclick=()=>$('file').click();$('file').onchange=async e=>{let f=e.target.files[0];if(!f)return;try{pts=parse(await f.text());put(K,pts);prep();draw();msg('GPX importé · '+pts.length+' points · '+fmt(total))}catch(err){msg('Import : '+err.message)}e.target.value=''};
$('gpsBtn').onclick=()=>watch===null?start():stop();$('eco').onchange=e=>{eco=e.target.checked;msg(eco?'Économie activée : précision GPS potentiellement réduite':'Mode normal activé');if(watch!==null){stop();start()}};$('plus').onclick=()=>map?.zoomIn();$('minus').onclick=()=>map?.zoomOut();$('fit').onclick=()=>route?map.fitBounds(route.getBounds(),{padding:[35,35]}):msg('Importer GPX');$('locate').onclick=()=>window._atlasLast?map?.setView([window._atlasLast.lat,window._atlasLast.lon],16):msg('Activer GPS');$('full').onclick=()=>{document.querySelector('.mapCard').classList.toggle('mapExpanded');setTimeout(()=>map?.invalidateSize(),100)};
$('north').onclick=()=>msg('La carte reste orientée au nord. Le cap du téléphone apparaît dans la barre et sur le point bleu : rotation de carte non disponible dans Leaflet standard.');
$('compass').onclick=async()=>{if(!window.DeviceOrientationEvent){msg('Capteur boussole indisponible : cap GPS possible en mouvement');return}try{if(typeof DeviceOrientationEvent.requestPermission==='function'&&await DeviceOrientationEvent.requestPermission()!=='granted')throw Error('Autorisation refusée');window.addEventListener('deviceorientationabsolute',orientation,true);window.addEventListener('deviceorientation',orientation,true);compass=true;$('compass').textContent='Boussole activée';msg('Boussole demandée : cap affiché si le téléphone fournit le nord absolu')}catch(e){msg('Boussole : '+e.message)}};
$('return').onclick=()=>{if(!map||walk.length<2){msg('Il faut au moins deux positions enregistrées');return}if(returnLine){map.removeLayer(returnLine);returnLine=null;$('return').textContent='Voir mon retour';return}returnLine=L.polyline(walk.slice().reverse().map(p=>[p.lat,p.lon]),{color:'#f28b2b',weight:6,dashArray:'9 7'}).addTo(map);map.fitBounds(returnLine.getBounds());$('return').textContent='Masquer le retour';msg('Orange = chemin enregistré en sens inverse, non vérifié pour la praticabilité')};
$('exportWalk').onclick=()=>{if(walk.length<2){msg('Aucune trace à exporter');return}let xml='<?xml version="1.0"?><gpx version="1.1" creator="Atlas Rando" xmlns="http://www.topografix.com/GPX/1/1"><trk><name>Trace parcourue</name><trkseg>'+walk.map(p=>`<trkpt lat="${p.lat}" lon="${p.lon}"><time>${new Date(p.t).toISOString()}</time></trkpt>`).join('')+'</trkseg></trk></gpx>';download('trace-atlas.gpx',xml,'application/gpx+xml')};
$('clearWalk').onclick=()=>{if(confirm('Effacer la trace parcourue enregistrée sur cet appareil ?')){walk=[];put(W,walk);drawWalk();if(returnLine){map.removeLayer(returnLine);returnLine=null}}};
$('save').onclick=()=>{let arr=get(J)||[];arr.push({name:$('name').value,date:$('date').value,rating:$('rating').value,notes:$('notes').value});if(put(J,arr)){entries();msg('Carnet enregistré sur cet appareil')}};$('exportJournal').onclick=()=>download('carnet-atlas.json',JSON.stringify(get(J)||[],null,2),'application/json');
$('diagnostic').onclick=async()=>{let reg='non pris en charge';try{reg=('serviceWorker'in navigator)?(await navigator.serviceWorker.getRegistration())?.active?'actif':'inactif':reg}catch(e){reg=e.message}$('diag').textContent=['Connexion : '+(navigator.onLine?'en ligne':'hors ligne'),'Service worker : '+reg,'GPX : '+pts.length+' points','Trace enregistrée : '+walk.length+' points','Carnet : '+(get(J)||[]).length+' sortie(s)','Carte : '+(map?'Leaflet chargé':'indisponible'),'Boussole : '+(heading===null?'pas de cap':'cap '+Math.round(heading)+'°')].join('\n')};
if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(e=>console.warn(e))}
window.addEventListener('load',init)})();